version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=rehearsal-scheduler
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/rehearsal-scheduler
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost
    ports:
      - "5000:5000"
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: